default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        name: ruff lint (no fixes)
        args: ["--no-fix"]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--strict, -c=.yamllint]

  - repo: local
    hooks:
      - id: yamlfmt
        name: yamlfmt
        entry: yamlfmt
        language: system
        stages: [commit]
        types: [yaml]

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt
        args: ["-w", "-i", "2", "-ci"]
        files: ^scripts/.*\.sh$

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["--severity=style", "--external-sources", "--exclude=SC1091"]
        files: ^scripts/.*\.sh$
