name: sallm-ner
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - transformers
  - accelerate
  - datasets
  - wandb
  - pyyaml
  - scipy
  - numpy
  - pydantic
  - regex
  - black
  - mypy
  - pytest
  - pip:
    - "causal-conv1d"
    - "mamba-ssm"
    - "types-pyyaml"
    - "tabulate"