name: sallm-ner
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  # Core ML/Python stack
  - python=3.12
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - transformers
  - tokenizers
  - accelerate
  - datasets
  - wandb
  - pyyaml
  - scipy
  - numpy
  - pydantic
  - regex

  # Build dependencies for Mamba
  - gxx_linux-64

  # Dev tools
  - black
  - mypy
  - pytest

  # Pip-only or specific version dependencies
  - pip:
    - "causal-conv1d"
    # - "mamba-ssm"
    - "types-pyyaml"
