mode: FINETUNE

wandb:
  project: "sallm-ft"
  name: "llama-125m-afriinstruct-multilingual"

model:
  architecture: "llama"
  init_checkpoint: "${oc.env:SCRATCH}/masters/sallm/checkpoints/sallm-llama-125m/final_model"

peft:
  method: "lora"
  kwargs: {r: 128, lora_alpha: 256, lora_dropout: 0.1}

dataset:
  hf_name: "llama-lang-adapt/AfriInstruct-Data"
  subset: null
  languages: ["eng", "zul", "xho", "sot", "nso", "tsn", "tso", "afr", "ssw", "ven", "nbl"]
  task: INSTRUCTION
  splits: {train: "train", val: "validation"}
  templates: []
  packing: false
  assistant_only_loss: true
  max_seq_length: 2048

tokenizer: {path: "${oc.env:HOME}/masters/sallm/tokenizer/sallm_bpe_tokenizer"}

training:
  output_dir: "${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_llama_125m_instruct_multilingual"
  logging_dir: "${oc.env:SCRATCH}/masters/sallm/logs/ft_llama_125m_instruct_multilingual"
  run_name: "llama-125m-afriinstruct-lora-multilingual"
  learning_rate: 3.0e-5
  adam_beta2: 0.95
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.1
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 16
  num_train_epochs: 5
  bf16: true
  logging_steps: 25
  eval_strategy: "epoch"
  save_strategy: "no"
  dataloader_num_workers: 4
  gradient_checkpointing: false
  label_names: []
  report_to: "wandb"
  ddp_find_unused_parameters: false
