mode: FINETUNE

wandb:
  project: "sallm-ft"
  name: "llama-125m-afrihg-eng"

model:
  architecture: "llama"
  init_checkpoint: "${oc.env:SCRATCH}/masters/sallm/checkpoints/sallm-llama-125m/final_model"

peft:
  method: "lora"
  kwargs:
    r: 256
    lora_alpha: 512
    lora_dropout: 0.1

dataset:
  hf_name: "dadelani/AfriHG"
  subset: "eng"
  splits: {train: "train", val: "validation"}
  task: INSTRUCTION
  templates:
    - {id: "afrihg_headline/v1", weight: 1}
  template_choice: ALL
  packing: false
  assistant_only_loss: true
  max_seq_length: 2048

tokenizer: {path: "${oc.env:HOME}/masters/sallm/tokenizer/sallm_bpe_tokenizer"}

training:
  output_dir: "${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_llama_125m_afrihg_eng"
  logging_dir: "${oc.env:SCRATCH}/masters/sallm/logs/ft_llama_125m_afrihg_eng"
  run_name: "llama-125m-afrihg-eng"
  learning_rate: 0.00013413657020600855
  adam_beta2: 0.95
  lr_scheduler_type: "linear"
  warmup_ratio: 0.05
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 16
  num_train_epochs: 3
  weight_decay: 0.0970951241029608
  max_grad_norm: 1.0
  bf16: true
  gradient_checkpointing: false
  label_smoothing_factor: 0.05
  logging_steps: 10
  logging_first_step: true
  eval_strategy: "epoch"
  save_strategy: "no"
  dataloader_num_workers: 8
  eval_accumulation_steps: 1
  report_to: "wandb"
  ddp_find_unused_parameters: false
