defaults:
  - defaults/datasets/sa_general@_here_
  - defaults/common@_here_
  - defaults/arch/llama@_here_
  - _self_
wandb:
  name: llama-125m-sa-general-all
peft:
  kwargs:
    lora_dropout: 0
dataset:
  subset: null
  max_seq_length: 2048
  languages: null
  mix_epoch_size: sum
  mix_max_prob: 0.35
  mix_min_prob: 0.05
  mix_temperature: 0.0
  mix_weights:
    afrihg: 1.0
    ner: 1.0
    news: 1.0
    pos: 1.0
    sib: 1.0
    t2x: 1.0
training:
  output_dir: ${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_llama_125m_sa_general_all
  logging_dir: ${oc.env:SCRATCH}/masters/sallm/logs/ft_llama_125m_sa_general_all
  run_name: llama-125m-sa-general-all
  learning_rate: 1.053899173290038e-05
  weight_decay: 0.003722056462983181
  gradient_accumulation_steps: 8
  lr_scheduler_type: constant_with_warmup
  warmup_ratio: 0
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  num_train_epochs: 5
  gradient_checkpointing: true
  dataloader_num_workers: 4
