defaults:
  - defaults/datasets/afrihg@_here_
  - defaults/common@_here_
  - defaults/arch/llama@_here_
  - _self_
wandb:
  name: llama-125m-afrihg-xho
peft:
  kwargs:
    lora_dropout: 0.05
dataset:
  subset: xho
  max_seq_length: 2048
training:
  output_dir: ${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_llama_125m_afrihg_xho
  logging_dir: ${oc.env:SCRATCH}/masters/sallm/logs/ft_llama_125m_afrihg_xho
  run_name: llama-125m-afrihg-xho
  learning_rate: 4.338264569149352e-05
  weight_decay: 0.031028218096256
  gradient_accumulation_steps: 16
  lr_scheduler_type: constant_with_warmup
  per_device_train_batch_size: 8
  num_train_epochs: 3
  gradient_checkpointing: true
  dataloader_num_workers: 4
  metric_for_best_model: eval_all_chrf
  greater_is_better: true
  label_smoothing_factor: 0.05
  logging_first_step: true
generation_decoding:
  early_stopping: true
  length_penalty: 0.7
  num_beams: 5
  strategy: beam
