mode: FINETUNE

wandb:
  project: "sallm-ft"
  name: "llama-125m-t2x-xho"

model:
  architecture: "llama"
  init_checkpoint: "${oc.env:SCRATCH}/masters/sallm/checkpoints/sallm-llama-125m/final_model"

dataset:
  hf_name: "github:francois-meyer/t2x"
  subset: "xho"
  splits: {train: "train", val: "validation"}
  task: INSTRUCTION
  templates:
    - {id: "t2x_verbalisation/v1", weight: 1}
  template_choice: ALL
  packing: false
  assistant_only_loss: true
  max_seq_length: 1024

tokenizer: {path: "${oc.env:HOME}/masters/sallm/tokenizer/sallm_bpe_tokenizer"}

training:
  output_dir: "${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_llama_125m_t2x_xho"
  logging_dir: "${oc.env:SCRATCH}/masters/sallm/logs/ft_llama_125m_t2x_xho"
  run_name: "llama-125m-t2x-xho"
  learning_rate: 2.7180064756827244e-05
  adam_beta2: 0.95
  lr_scheduler_type: "linear"
  warmup_ratio: 0
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 8
  num_train_epochs: 4
  weight_decay: 0.09458873087309864
  max_grad_norm: 1.0
  bf16: true
  gradient_checkpointing: false  # sweep: true
  label_smoothing_factor: 0.05
  logging_steps: 10
  logging_first_step: true
  eval_strategy: "epoch"
  save_strategy: "no"
  dataloader_num_workers: 8
  eval_accumulation_steps: 1
  report_to: "wandb"
  ddp_find_unused_parameters: false
