mode: FINETUNE
wandb:
  project: sallm-ft
  name: mamba-125m-sib-all
model:
  architecture: mamba2
  init_checkpoint: anrilombard/sallm-mamba-125m
peft:
  method: lora
  kwargs:
    r: 128
    lora_alpha: 512
    lora_dropout: 0
    target_modules:
      - in_proj
      - x_proj
      - embeddings
dataset:
  hf_name: Davlan/sib200
  subset: null
  languages:
    - afr_Latn
    - eng_Latn
    - nso_Latn
    - sot_Latn
    - xho_Latn
    - zul_Latn
  task: CLASSIFICATION
  splits:
    train: train
    val: validation
  templates:
    - id: sib_topic_classification/lm_eval_p1
      weight: 1.0
    - id: sib_topic_classification/lm_eval_p2
      weight: 1.0
    - id: sib_topic_classification/lm_eval_p3
      weight: 1.0
    - id: sib_topic_classification/lm_eval_p4
      weight: 1.0
    - id: sib_topic_classification/lm_eval_p5
      weight: 1.0
  template_choice: CYCLE
  label_column: category
  packing: false
  assistant_only_loss: true
  max_seq_length: 1024
tokenizer:
  path: ${oc.env:HOME}/masters/sallm/tokenizer/sallm_bpe_tokenizer
training:
  output_dir: ${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_mamba_125m_sib_all
  logging_dir: ${oc.env:SCRATCH}/masters/sallm/logs/ft_mamba_125m_sib_all
  run_name: mamba-125m-sib-lora-all
  learning_rate: 7.060255207370642e-05
  weight_decay: 0.17739696605700747
  adam_beta2: 0.95
  max_grad_norm: 1.0
  gradient_accumulation_steps: 4
  lr_scheduler_type: linear
  warmup_ratio: 0.1
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 4
  eval_accumulation_steps: 1
  num_train_epochs: 10
  bf16: true
  gradient_checkpointing: false
  logging_steps: 10
  eval_strategy: epoch
  save_strategy: 'no'
  dataloader_num_workers: 8
  report_to: wandb
  ddp_find_unused_parameters: true
hub:
  enabled: true
  organization: anrilombard
  private: true
  push_adapter: true
  push_merged: false
