mode: FINETUNE

wandb: {project: "sallm-ft", name: "mamba-125m-injongo-intent-xho"}

model:
  architecture: "mamba2"
  init_checkpoint: "${oc.env:SCRATCH}/masters/sallm/checkpoints/sallm-mamba-125m/final_model"

peft:
  method: "lora"
  kwargs: {r: 128, lora_alpha: 256, lora_dropout: 0.1, target_modules: ["in_proj", "x_proj", "embeddings", "out_proj"]}

dataset:
  hf_name: "masakhane/InjongoIntent"
  subset: "xho"
  splits: {train: "train", val: "validation"}
  task: CLASSIFICATION
  label_column: "intent"
  templates: [{id: "injongointent_intent_classification/v5", weight: 1.0}]
  packing: false
  assistant_only_loss: true
  max_seq_length: 1024

tokenizer: {path: "${oc.env:HOME}/masters/sallm/tokenizer/sallm_bpe_tokenizer"}

training:
  output_dir: "${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_mamba_125m_injongointent_xho"
  logging_dir: "${oc.env:SCRATCH}/masters/sallm/logs/ft_mamba_125m_injongointent_xho"
  run_name: "mamba-125m-injongo-intent-xho"
  learning_rate: 3.838646036544591e-05
  adam_beta2: 0.95
  max_grad_norm: 1.0
  gradient_accumulation_steps: 16
  lr_scheduler_type: "constant_with_warmup"
  warmup_ratio: 0
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 4
  eval_accumulation_steps: 1
  num_train_epochs: 20
  bf16: true
  gradient_checkpointing: true
  logging_steps: 10
  eval_strategy: "epoch"
  save_strategy: "no"
  dataloader_num_workers: 8
  report_to: "wandb"
  ddp_find_unused_parameters: true
  weight_decay: 0.1770125416416487
