defaults:
  - defaults/datasets/masakhaner@_here_
  - defaults/common@_here_
  - defaults/arch/xlstm@_here_
  - _self_
wandb:
  name: xlstm-125m-ner-xho
peft:
  kwargs:
    r: 16
    lora_alpha: 32
    lora_dropout: 0.05
    target_modules:
      - q
      - k
      - v
      - out_proj
dataset:
  subset: null
  max_seq_length: 2048
  languages:
    - xho
training:
  output_dir: ${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_xlstm_125m_ner_xho
  logging_dir: ${oc.env:SCRATCH}/masters/sallm/logs/ft_xlstm_125m_ner_xho
  run_name: xlstm-125m-ner-lora-finetune-xho
  learning_rate: 0.0004496585905434496
  weight_decay: 0.13449041980438445
  gradient_accumulation_steps: 16
  lr_scheduler_type: constant_with_warmup
  warmup_ratio: 0
  per_device_train_batch_size: 4
