defaults:
  - defaults/datasets/sib@_here_
  - defaults/common@_here_
  - defaults/arch/xlstm@_here_
  - _self_
wandb:
  name: xlstm-125m-sib-afr
dataset:
  subset: afr_Latn
  max_seq_length: 1024
training:
  output_dir: ${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_xlstm_125m_sib_afr
  logging_dir: ${oc.env:SCRATCH}/masters/sallm/logs/ft_xlstm_125m_sib_afr
  run_name: xlstm-125m-sib-lora-afr
  learning_rate: 9.23415716207728e-05
  weight_decay: 0.1340385821569752
  gradient_accumulation_steps: 2
  lr_scheduler_type: constant_with_warmup
  warmup_ratio: 0
  num_train_epochs: 10
