program: run.py
method: bayes
metric:
  name: val/overall/f1-score
  goal: maximize
project: sallm-ner-finetuning
command:
  - ${env}
  - python
  - ${program}
  - --hpo
  - ${args}
parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1.0e-5
    max: 9.0e-5
  head_lr_multiplier:
    distribution: q_uniform
    min: 2
    max: 10
    q: 1
  weight_decay:
    distribution: uniform
    min: 0.0
    max: 0.1
  warmup_ratio:
    distribution: uniform
    min: 0.05
    max: 0.1
  num_train_epochs:
    value: 10
  batch_size:
    value: 16