project: "sallm-llama-hpo"
name: "llama-125m-bayesian-sweep"
run_cap: 50
# TODO add how many trials are expected
program: sallm.main
command:
  - ${interpreter}
  - -m
  - accelerate.commands.accelerate_cli
  - launch
  - -m
  - ${program}
  - --config_path
  - configs/base/llama_125m.yaml
  - ${args}
method: bayes
metric:
  name: eval/loss
  goal: minimize
parameters:
  gradient_accumulation_steps:
      values: [1, 2, 4, 8]
  # TODO: architectural bayesian sweep
  learning_rate:
    distribution: log_uniform
    # TODO fix this to use log_uniform_values if possible
    # min: ln(1e-5) ≈ -11.51
    # max: ln(6e-4) ≈ -7.42
    min: -11.51
    max: -7.42
  weight_decay:
    distribution: uniform
    min: 0.01
    max: 0.1
  warmup_ratio:
    distribution: uniform
    min: 0.01
    max: 0.06
  lr_scheduler_type:
    values: ["cosine", "linear"]
  adam_beta2:
    values: [0.95, 0.999]
  max_grad_norm:
    values: [1.0]
