program: src/main/sallm/main.py
command:
  - ${env}
  - python
  - ${program}
  - ${args}
method: bayes
metric:
  name: eval/loss
  goal: minimize
parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 6e-4
  weight_decay:
    distribution: uniform
    min: 0.01
    max: 0.1
  warmup_ratio:
    distribution: uniform
    min: 0.01
    max: 0.06
  lr_scheduler_type:
    values: ["cosine", "linear"]
  adam_beta2:
    values: [0.95, 0.999]
  max_grad_norm:
    values: [1.0]
