hf_name: "masakhane/InjongoIntent"
splits:
  train: "train"
  val: "validation"
task: CLASSIFICATION
label_column: "intent"
templates:
  - id: "injongointent_intent_classification/v5"
    weight: 1.0
packing: false
assistant_only_loss: true
max_seq_length: 2048
