defaults:
  - _self_
  - model: ???
  - data: ???
  - tokenizer: ???
  - training: ???
  - evaluation: ???
  - finetune: ???
  - pipeline: ???

mode: ???
wandb:
  project: sallm
  entity: anrilombard
