defaults:
  - _self_
  - model: ???
  - dataset: ???
  - tokenizer: ???
  - training: ???
  - evaluation: null
  - finetune: ???
  - pipeline: null

mode: ???
wandb:
  project: sallm
  entity: anrilombard
