name: Linter and Formatter Checks
'on': [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: false

      - run: poetry install --no-root

      - run: poetry run yamllint --strict -c .yamllint .
      - run: poetry run black --check .
